Stusd upgrades
Blueberryfi/Bloom-protocol pull request #31
Opened 2023-12-29 22:56 UTC by Gornutz

# Description

This PR addresses changes that were brought up in the audit of stUSD (stTBY) [H-08] Deposits of current TBY to stUSD immediately before a new TBY is deployed will cause double counting. To alleviate this issue the function `poke()` from stUSD has been introduced into the factory contract, such that it's called before deploying a new `BloomPool` to ensure that the values are up-to-date and avoid any double counting. In addition to that `lenderReturnFee`, `borrowerReturnFee` & `Treasury` have been removed from `BloomPools` as the first two have always been set to zero and are not necessary to the functionality as a result `Treasury` no longer needs to be included. Finally, the `BloomPoolFactory` has been made to be upgradeable so that there is no need to ever deploy another Factory contract besides a new implementation. This allows for the `BloomPool` instances to remain immutable by nature and future `BloomPool`s instances can be enhanced as needed.

## Type of change

- [X] Audit fix 
- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes
- [X] Complex code has been commented, including external interfaces
- [X] Tests are included for all code paths
- [X] The base branch is either `main`, or there's a description of how to merge

## Issue Resolution

stUSD / stTBY audit by 0x52 issue [H-08]

2023-12-29 23:45 UTC, 0xSpraggins requested changes
Looks good. Just one minor format change

2023-12-29 23:45 UTC, 0xSpraggins commented on src/helpers/ExchangeRateRegistry.sol
> +        uint256 delta = ((rate * BASE_RATE ) * timeElapsed) /
```suggestion
        uint256 delta = (rate * BASE_RATE * timeElapsed) / 
```
We can remove these parenthesis.

2023-12-30 00:12 UTC, 0xSpraggins requested changes

2023-12-30 00:12 UTC, 0xSpraggins commented on src/BloomPool.sol
> +
Extra Line got added. We can remove this as well

2023-12-30 00:12 UTC, 0xSpraggins commented on src/helpers/ExchangeRateRegistry.sol
> +        uint256 delta = (rate * BASE_RATE  * timeElapsed) /
```suggestion
        uint256 delta = (rate * BASE_RATE * timeElapsed) / 
```
Extra space can be removed

2023-12-30 04:12 UTC, 0xSpraggins approved these changes

2024-01-13 19:15 UTC, IAm0x52 approved these changes
Fix looks good. Bloom factory now pokes during creation to guarantee no double counting happens

2024-01-15 14:58 UTC, merged